import typing

from .dataset import Dataset
from .ops import Op

class Batch:
    '''
    A (mini)batch generated by the batch generator.
    '''

    def __init__(self):
        '''
        Ctor.
        '''

        self.data = None
        self.label = None
        self.idx = None

class BatchGenerator:
    '''
    Batch generator.
    Returned batches have the following properties:
      data: numpy array holding batch data of shape (s, SHAPE_OF_DATASET_SAMPLES).
      label: numpy array holding batch labels of shape (s, SHAPE_OF_DATASET_LABELS).
      idx: numpy array with shape (s,) encoding the indices of each sample in the original dataset.
    '''

    def __init__(self, dataset: Dataset, num: int, shuffle: bool, op: Op=None):
        '''
        Ctor.
        Dataset is the dataset to iterate over.
        num is the number of samples per batch. the number in the last batch might be smaller than that.
        shuffle controls whether the sample order should be preserved or not.
        op is an operation to apply to input samples.
        Raises TypeError on invalid argument types.
        Raises ValueError on invalid argument values, such as if num is > len(dataset).
        '''

        import numpy as np
        data=[]
        labels=[]
        indexes=[]
        batches=[]


        if(num>len(dataset)):
            raise ValueError
        if(len(dataset) % num!=0):
            num_of_batches = (len(dataset) // num) + 1
        else:
            num_of_batches = (len(dataset) // num)

        for x in dataset:
            data.append(x.data)
            labels.append(x.label)
            indexes.append(x.idx)

        data=np.array(data)
        labels=np.array(labels)
        indexes=np.array(indexes)



        if(shuffle==True):
            shuffler = np.random.permutation(len(data))
            data=data(shuffler)
            labels=labels(shuffler)
            indexes=indexes(shuffler)

        for i in range(num_of_batches):
            b=Batch()
            new_data=data[num * i:num * (i + 1)]
            if (op is not None):
                new_data = op(new_data)

            b.data=new_data
            b.label=labels[num * i:num * (i + 1)]
            b.idx=indexes[num * i:num * (i + 1)]
            batches.append(b)

        self.batches=batches

        pass

    def __len__(self) -> int:
        '''
        Returns the total number of batches the dataset is split into.
            This is identical to the total number of batches yielded every time the __iter__ method is called.
        '''

        return(len(self.batches))

    def __iter__(self) -> typing.Iterable[Batch]:
        '''
        Iterate over the wrapped dataset, returning the data as batches.
        '''

        for batch in self.batches:
            yield batch

